### ISSUE TITLE
Troubles while working with Yandex CR

### ISSUE THREAD

**Issue by helgisid** [deckhouse/k8s-image-availability-exporter#146]
Hi there, we have some troubles trying to make it work with yc cr. We get the following errors:
![image](https://github.com/deckhouse/k8s-image-availability-exporter/assets/153656596/5e373729-369d-4713-9f40-25e9190f268e)

But as I can see from readme it should use the secrets noted in PodSpecs of the container with no help.
The exporter was deployed by helm chart.
what do we do wrong?

**Comment by nabokihms** [comment]
@helgisid hello, sorry for the long delay. Could you please share what is in your secret (counseling the sensitive data)?

**Comment by wzzirro** [comment]
Issue can be closed,  problem was in permission insufficiently. Thank you
