### ISSUE TITLE
Add ability to customise pod annotations

### ISSUE THREAD

**Issue by artemiyplotnikov** [deckhouse/k8s-image-availability-exporter#170]
Please add ability to customise pod annotations for deployment k8s-image-availability-exporter
for example:
```
  template:
    metadata:
      {{- if .Values.k8sImageAvailabilityExporter.annotations }}
      annotations:
       {{- include .Values.k8sImageAvailabilityExporter.annotations . | nindent 8 }}
```

**Comment by nabokihms** [comment]
@artemiyplotnikov sure, but can you elaborate on why you need this? (This is important to know usescases for features).

**Comment by artemiyplotnikov** [comment]
First of all we use annotations for filtering and configuring scraping options.
For example:
```
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "{{ .Values.env.PROMETHEUS_PORT }}"
```
I know that there is another options to configure Prometheus scrape but it would multiply configuring options and hardenes

**Comment by nabokihms** [comment]
Closed by https://github.com/deckhouse/k8s-image-availability-exporter/pull/212
