### ISSUE TITLE
Command line options is hardcoded in chart

### ISSUE THREAD

**Issue by evgkrsk** [deckhouse/k8s-image-availability-exporter#24]
Now there is no usual way to change CLI options via helm chart: "--bind-address=:8080" is hardcoded in template.

**Comment by zuzzas** [comment]
If you've got time (or, perhaps, a working fix), I'd gladly merge it.

**Comment by Thorndike** [comment]
I hope this does it
https://github.com/flant/k8s-image-availability-exporter/pull/38

**Comment by evgkrsk** [comment]
https://github.com/deckhouse/k8s-image-availability-exporter/pull/38 - сегодня смержили.

Осталось начать публиковать чарт.
