### ISSUE TITLE
Deployment process streamlining

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/k8s-image-availability-exporter#6]
Streamline deployment, prepare proper kustomize or Helm templates.

**Comment by nabokihms** [comment]
1. Helm chart is the official installation way for the exporter
2. It is publically available on [artifacthub.io](https://artifacthub.io/packages/helm/k8s-image-availability-exporter/k8s-image-availability-exporter)
3. The CI is added for releasing new versions of the chart

**Comment by nabokihms** [comment]
I'm going to close the issue. Feel free to reopen it if there is something left.
