### ISSUE TITLE
Broken on Kubernetetes v1.25 due to removed `v1beta1.CronJob`

### ISSUE THREAD

**Issue by dominik-horb-umg** [deckhouse/k8s-image-availability-exporter#61]
On Kubernetes v1.25 the image is not working anymore due to the usage of the `v1beta1.CronJob` API that is deprecated since v1.21. The pod is CrashLooping with the following error message:

```
E1010 08:43:23.255855       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.CronJob: failed to list *v1beta1.CronJob: the server could not find the requested resource
```

**Comment by kantipov** [comment]
Created pull request https://github.com/deckhouse/k8s-image-availability-exporter/pull/65
