### ISSUE TITLE
Публичный helm чарт

### ISSUE THREAD

**Issue by patsevanton** [deckhouse/k8s-image-availability-exporter#76]
Приветствую.
Прошу рассмотреть возможность публикации/создания публичного helm чарта для [k8s-image-availability-exporter](https://github.com/deckhouse/k8s-image-availability-exporter)

**Comment by nabokihms** [comment]
The public helmchart is now available on artifucthub.io
https://artifacthub.io/packages/helm/k8s-image-availability-exporter/k8s-image-availability-exporter
